### ISSUE TITLE
Can the theme colors be changed dynamically ?

### ISSUE THREAD

**Issue by RahulRvR** [StevenByle/Android-Material-Themes-Demo#6]
Great example on using appcompat theme, really appreciate it. I see there are separate styles for themes. Can the theme attributes like colorPrimary, colorAccent be changed dynamically ? I would like to theme the app with a color which will be known only during the runtime.

**Comment by StevenByle** [comment]
@RahulRvR Unfortunately you cannot change an attribute applied to a style or theme at runtime, this is because those attributes are read by views when they are inflated, and are not expected to be transient. You can use drawable tinting with color state lists to color your UI elements at run time. This approach is a little more work, as some UI elements are made up of multiple drawables, and you will need to cast them to their appropriate AppCompat version before tinting.
